INSERT INTO public.actores(
	actores_reparto_id, nombre_actor, "Personaje", sexualidad)
	VALUES
  (1, 'Lily Sullivan', 'Beth', 1),
  (2, 'Alyssa Sutherland', 'Ellie', 1),
  (3, 'Morgan Davies', 'Danny', 2),
  (4, 'Gabrielle Echols', 'Bridget', 0),
  (5, 'Nell Fisher', 'Kassie', 1),
  (6, 'Anna-Maree Thomas', 'Jessica', 1),
  (7, 'Mirabai Pease', 'Teresa', 1),
  (8, 'Richard Crouchley', 'Caleb', 2),
  (9, 'Jayden Daniels', 'Gabriel', 2),
  (10, 'Mark Mitchinson', 'Mr. Fonda', 2),
  (11, 'Tai Wano', 'Scott', 0),
  (12, 'Billy Reynolds-McCarthy', 'Jake', 0),
  (13, 'Noah Paul', 'Bruce', 2),
  (14, 'Melissa Xiao', 'Newscaster', 0),
  (15, 'Bruce Campbell', 'Priest (voice)', 2), 
  (16, 'Paul Rudd', 'Scott Lang / Ant-Man', 2),
  (17, 'Evangeline Lilly', 'Hope van Dyne / The Wasp', 1),
  (18, 'Jonathan Majors', 'Kang the Conqueror', 2),
  (19, 'Kathryn Newton', 'Cassie Lang', 1),
  (20, 'Michelle Pfeiffer', 'Janet van Dyne', 1),
  (21, 'Michael Douglas', 'Dr. Hank Pym', 2),
  (22, 'Corey Stoll', 'M.O.D.O.K.', 2),
  (23, 'Bill Murray', 'Lord Krylar', 2),
  (24, 'William Jackson Harper', 'Quaz', 2),
  (25, 'David Dastmalchian', 'Veb (voice)', 2),
  (26, 'Jamie Andrew Cutler', 'XOLUM', 2),
  (27, 'Katy OBrian', 'Jentorra', 1),
  (28, 'Mark Weinman', 'Patrol Police Officer / On-Set M.O.D.O.K.', 0),
  (29, 'Randall Park', 'Jimmy Woo', 2),
  (30, 'Ross Mullan', 'Axia Restaurant Maitre D', 2),
  (31, 'Tom Clark', 'Axia Restaurant Bartender', 2),
  (32, 'Leon Cooke', 'Axia Restaurant Bartender', 2),
  (33, 'Nathan Blees', 'Axia Restaurant Waiter', 2),
  (34, 'Durassie Kiangangu', 'Axia Restaurant Waiter', 0),
  (35, 'Liran Nathan', 'Axia Restaurant Waiter', 0),
  (36, 'Sam Symons', 'Krylars Valet', 2),
  (37, 'Grahame Fox', 'Broccoli Man', 0),
  (38, 'Nicola Peluso', 'Corrections Officer', 2),
  (39, 'Harrison Daniels', 'Booking Officer', 0),
  (40, 'Brahmdeo Shannon Ramana', ¿'Hopes Assistant', 0),
  (41, 'Russell Balogh', 'Nomad Leader', 0),
  (42, 'Leonardo Taiwo', 'Quantumnaut Scientist', 0),
  (43, 'Osian Roberts', 'Quantumnaut Lieutenant', 2),
  (44, 'Lucas Gerstel', 'Book Signing Audience', 0),
  (45, 'Mia Gerstel', 'Book Signing Audience', 2),
  (46, 'Tracy Jeffrey', 'Book Signing Audience', 2),
  (47, 'Dinah Jeffrey', 'Book Signing Audience', 2),
  (48, 'Judy Jeffrey', 'Book Signing Audience', 2),
  (49, 'John Nayagam', 'Book Signing Audience', 2),
  (50, 'Greta Nayagam', 'Book Signing Audience', 2),
  (51, 'Cathy Chan', 'Book Signing Audience', 2),
  (52, 'Adam Sai', 'Book Signing Audience', 2),
  (53, 'Jamie Sai', 'Book Signing Audience', 2),
  (54, 'Jakari Fraser', 'Young Ant-Man Fan', 1),
  (55, 'Patricia Belcher', 'Ant-Man Fan', 1),
  (56, 'Mark Oliver Everett', 'Jogger with Dog', 2),
  (57, 'Ruben Rabasa', 'Café Owner', 0),
  (58, 'Melanie Garcia', 'Barista', 2),
  (59, 'Gregg Turkington', 'Dale', 1),
  (60, 'Sierra Katow', 'Waiter', 2),
  (61, 'Ryan Bergara', 'Toasting Man', 1),
  (62, 'Marielle Scott', 'Toasting Woman', 2),
  (63, 'Jake Millgard', 'Jogger', 1),
  (64, 'Dey Young', 'Woman with Dog', 1),
  (65, 'Briza Covarrubias', 'Hostess', 2),
  (66, 'Tess Aubert', 'Waitstaff', 2),
  (67, 'David J. Castillo', 'Waitstaff', 2),
  (68, 'Sir Cornwell', 'Waitstaff', 2),
  (69, 'Alan Heitz', 'Waitstaff', 2),
  (70, 'Esther McAuley', 'Alien World Citizen', 2),
  (71, 'Aisling Maria Andreica', 'Alien World Citizen', 2),
  (72, 'Milton Lopes', 'Alien World Citizen', 2),
  (73, 'Roger Craig Smith', 'Quantumnaut Voices (voice)', 1),
  (74, 'Matthew Wood', 'Quantumnaut Voices (voice)', 1),
  (75, 'Loveday Smith', 'Janet Van Dyne Acting Double', 2),
  (76, 'John Townsend', 'Lord Krylar Acting Photo Double', 2),
  (77, 'Tom Hiddleston', 'Loki (uncredited)', 2),
  (78, 'Owen Wilson', 'Mobius M. Mobius (uncredited)', 1),
  (79, 'Abby Ryder Fortson', 'Cassie Lang (archive footage) (uncredited)', 1);
  