-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.actores
(
    actores_reparto_id integer NOT NULL,
    nombre_actor text COLLATE pg_catalog."default" NOT NULL,
    "Personaje" text COLLATE pg_catalog."default" NOT NULL,
    sexualidad integer NOT NULL,
    CONSTRAINT actores_reparto_pkey PRIMARY KEY (actores_reparto_id)
);

CREATE TABLE IF NOT EXISTS public.actores_peliculas
(
    id integer NOT NULL DEFAULT nextval('actores_peliculas_id_seq'::regclass),
    peliculas_id integer NOT NULL,
    actores_id integer NOT NULL,
    CONSTRAINT actores_peliculas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.generos
(
    movie_genres_id integer NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT movie_genres_pkey PRIMARY KEY (movie_genres_id)
);

CREATE TABLE IF NOT EXISTS public.genres_map
(
    id integer NOT NULL,
    movie_title_id integer NOT NULL,
    movie_genres_id integer NOT NULL,
    CONSTRAINT genres_map_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.peliculas
(
    movie_titles_id integer NOT NULL,
    titulo text COLLATE pg_catalog."default" NOT NULL,
    puntuacion integer NOT NULL,
    fecha_salida date NOT NULL,
    para_adultos boolean NOT NULL,
    reviews integer,
    CONSTRAINT movie_titles_pkey PRIMARY KEY (movie_titles_id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    reviews_id integer NOT NULL,
    comentarios text COLLATE pg_catalog."default" NOT NULL,
    rating integer NOT NULL,
    fecha_creacion date NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (reviews_id)
);

CREATE TABLE IF NOT EXISTS public.sexualidad
(
    generos_actores_id integer NOT NULL,
    genero text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT generos_actores_pkey PRIMARY KEY (generos_actores_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL,
    username "char"[] NOT NULL,
    password "char"[] NOT NULL,
    email "char"[] NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.actores
    ADD CONSTRAINT "FK_sexualidad" FOREIGN KEY (sexualidad)
    REFERENCES public.sexualidad (generos_actores_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.actores_peliculas
    ADD CONSTRAINT "FK_actores_id" FOREIGN KEY (actores_id)
    REFERENCES public.actores (actores_reparto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.actores_peliculas
    ADD CONSTRAINT "FK_peli_id" FOREIGN KEY (peliculas_id)
    REFERENCES public.peliculas (movie_titles_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.genres_map
    ADD CONSTRAINT "FK_movie_genres_id" FOREIGN KEY (movie_genres_id)
    REFERENCES public.generos (movie_genres_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.genres_map
    ADD CONSTRAINT "FK_movie_title_id" FOREIGN KEY (movie_title_id)
    REFERENCES public.peliculas (movie_titles_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.peliculas
    ADD CONSTRAINT "FK_review_id" FOREIGN KEY (reviews)
    REFERENCES public.reviews (reviews_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;